sudo: false
language: elixir
elixir:
  - 1.4.4
otp_release:
  - 18.3
  - 19.3
script:
  - mix test
after_script:
  - MIX_ENV=test mix inch.report
matrix:
  exclude:
  - elixir: 1.1.1
    otp_release: 19.3
addons:
  apt:
    packages:
      - mosquitto
