sudo: false
dist: trusty
language: elixir
addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.mosquitto.org/debian wheezy main'
        key_url: 'http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key'
    packages:
      - mosquitto
elixir:
  - 1.4.4
otp_release:
  - 18.3
  - 19.3
script:
  - mix test
after_script:
  - MIX_ENV=test mix inch.report
cache:
  directories:
    - deps
