sudo: sudo
dist: trusty
language: elixir
addons:
  apt:
    packages:
      - mosquitto
elixir:
  - 1.4.4
otp_release:
  - 18.3
  - 19.3
script:
  - sudo cp support/mosquitto.conf /etc/mosquitto
  - sudo service mosquitto restart
  - cat /etc/mosquitto/mosquitto.conf
  - netstat -tulpen
  - cat /var/log/mosquitto.log
  - mix test
  - cat /var/log/mosquitto.log
after_script:
  - MIX_ENV=test mix inch.report
