sudo: false
dist: trusty
language: elixir
addons:
  apt:
    packages:
      - mosquitto
services: mosquitto
elixir:
  - 1.4.4
otp_release:
  - 18.3
  - 19.3
script:
  - cat /etc/mosquitto/mosquitto.conf
  - netstat -tulpen
  - cat /var/log/mosquitto/mosquitto.log
  - mix test
  - cat /var/log/mosquitto/mosquitto.log
after_script:
  - MIX_ENV=test mix inch.report
matrix:
  exclude:
  - elixir: 1.1.1
    otp_release: 19.3
