sudo: false
dist: trusty
language: elixir
addons:
  apt:
    sources:
    - sourceline: deb http://repo.mosquitto.org/debian wheezy main
      key_url: http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
    packages:
    - mosquitto
elixir:
- 1.4.4
otp_release:
- 18.3
- 19.3
script:
- mix test
- mix credo
- mix inch.report
cache:
  directories:
  - deps
  - _build
notifications:
  email:
  - tim@buchwaldt.ws
deploy:
  provider: script
  script: >-
     mix deps.get &&
     mix hex.config username "$HEX_USERNAME" &&
     (mix hex.config encrypted_key "$HEX_ENCRYPTED_KEY" > /dev/null 2>&1) &&
     (echo "$HEX_PASSPHRASE"\\nY | mix hex.publish) &&
     mix clean &&
     mix deps.clean --all
  on:
    tags: true
    otp_release: "19.3"
